tmdb:
  base-url: https://api.themoviedb.org
  api-version: 3
  uri:
    search:
      multi: /search/multi
    movie:
      now-playing: /movie/now_playing
      details: /movie/{movie_id}
    genre:
      list: /genre/list

