tmdb:
  base-url: https://api.themoviedb.org
  api-version: 3
  image:
    size: original
    url: https://image.tmdb.org/t/p
  uri:
    search:
      multi: /search/multi
    discover:
      movie: /discover/movie
      tv-show: /discover/tv
    trending:
      movie: trending/movie/{time_window}
    movie:
      now-playing: /movie/now_playing
      popular: /movie/popular
      top-rated: /movie/top_rated
      details: /movie/{movie_id}
      credits: /movie/{movie_id}/credits
    tv-show:
      airing-today: /tv/airing_today
    genre:
      list: /genre/list
      movie: /genre/movie/list
      tv-show: /genre/tv/list

